-- =========================================================================
-- VESTIS AI Database Initialization Script
-- Paste this script into the Supabase SQL Editor and click "Run"
-- =========================================================================

-- 1. Create Profiles Table (Digital Twin Info)
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  height numeric default 160,
  weight numeric default 50,
  gender text default 'female',
  avatar_url text,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS) on Profiles
alter table public.profiles enable row level security;

-- Policies for Profiles
create policy "Users can view their own profile." on public.profiles
  for select using (auth.uid() = id);

create policy "Users can update their own profile." on public.profiles
  for update using (auth.uid() = id);

create policy "Users can insert their own profile." on public.profiles
  for insert with check (auth.uid() = id);


-- 2. Create Custom Wardrobe Items Table
create table if not exists public.wardrobe_items (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  cat text not null,
  name text not null,
  price text default '私有單品',
  img_url text not null,
  is_external boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on Wardrobe
alter table public.wardrobe_items enable row level security;

-- Policies for Wardrobe
create policy "Users can view their own wardrobe items." on public.wardrobe_items
  for select using (auth.uid() = user_id);

create policy "Users can insert their own wardrobe items." on public.wardrobe_items
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own wardrobe items." on public.wardrobe_items
  for update using (auth.uid() = user_id);

create policy "Users can delete their own wardrobe items." on public.wardrobe_items
  for delete using (auth.uid() = user_id);


-- 3. Create Deleted Default Items Table
create table if not exists public.deleted_default_items (
  user_id uuid references auth.users on delete cascade not null,
  item_id integer not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  primary key (user_id, item_id)
);

-- Enable RLS
alter table public.deleted_default_items enable row level security;

-- Policies
create policy "Users can view their own deleted defaults list." on public.deleted_default_items
  for select using (auth.uid() = user_id);

create policy "Users can add items to their deleted defaults list." on public.deleted_default_items
  for insert with check (auth.uid() = user_id);

create policy "Users can remove items from their deleted defaults list." on public.deleted_default_items
  for delete using (auth.uid() = user_id);


-- 4. Create Favorites Table
create table if not exists public.favorites (
  user_id uuid references auth.users on delete cascade not null,
  item_id bigint not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  primary key (user_id, item_id)
);

-- Enable RLS
alter table public.favorites enable row level security;

-- Policies
create policy "Users can view their own favorites." on public.favorites
  for select using (auth.uid() = user_id);

create policy "Users can add favorites." on public.favorites
  for insert with check (auth.uid() = user_id);

create policy "Users can delete favorites." on public.favorites
  for delete using (auth.uid() = user_id);


-- 5. Create Outfit Logs Table
create table if not exists public.outfit_logs (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users on delete cascade not null,
  outfit jsonb not null,
  result_img_url text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.outfit_logs enable row level security;

-- Policies
create policy "Users can view their own outfit logs." on public.outfit_logs
  for select using (auth.uid() = user_id);

create policy "Users can add outfit logs." on public.outfit_logs
  for insert with check (auth.uid() = user_id);

create policy "Users can delete outfit logs." on public.outfit_logs
  for delete using (auth.uid() = user_id);


-- =========================================================================
-- 6. Create Gemini Sessions Table (For cloud-based auto-synthesis sync)
-- =========================================================================
create table if not exists public.gemini_sessions (
  user_id uuid references auth.users on delete cascade primary key,
  payload jsonb,
  result text,
  status text default 'pending',
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on Gemini Sessions
alter table public.gemini_sessions enable row level security;

-- Policies (Allows anonymous Userscript to query and update based on user_id)
create policy "Allow anyone to select gemini sessions." on public.gemini_sessions
  for select using (true);

create policy "Allow anyone to insert gemini sessions." on public.gemini_sessions
  for insert with check (true);

create policy "Allow anyone to update gemini sessions." on public.gemini_sessions
  for update using (true);

create policy "Allow anyone to delete gemini sessions." on public.gemini_sessions
  for delete using (true);


-- =========================================================================
-- 6b. Gemini Payloads Table (Vercel 雲端合成專用：以 session_id 為鍵，
--     讓訪客與登入用戶皆可透過 Supabase 傳遞穿搭素材與合成結果，
--     不再依賴本機中繼伺服器或 window.opener)
-- =========================================================================
create table if not exists public.gemini_payloads (
  session_id text primary key,
  payload jsonb,
  result text,
  status text default 'pending',
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on Gemini Payloads
alter table public.gemini_payloads enable row level security;

-- Policies (開放匿名 Userscript 依 session_id 讀寫)
create policy "Allow anyone to select gemini payloads." on public.gemini_payloads
  for select using (true);

create policy "Allow anyone to insert gemini payloads." on public.gemini_payloads
  for insert with check (true);

create policy "Allow anyone to update gemini payloads." on public.gemini_payloads
  for update using (true);

create policy "Allow anyone to delete gemini payloads." on public.gemini_payloads
  for delete using (true);


-- =========================================================================
-- 7. Trigger to Automatically Create Profile Row on User Sign-Up
-- =========================================================================
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, height, weight, gender, avatar_url)
  values (new.id, 160, 50, 'female', null);
  return new;
end;
$$ language plpgsql security definer;

-- Drop trigger if exists to avoid errors on rerun
drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- =========================================================================
-- Instructions for Supabase Storage Setup:
-- 1. Go to "Storage" panel in Supabase Dashboard.
-- 2. Create a new bucket named "wardrobe" (make it Public).
-- 3. In the bucket settings, add a policy under "Allowed Operations":
--    - SELECT: Allow anyone (or check "Public" bucket).
--    - INSERT/DELETE/UPDATE: Check "Authenticated Users" only, with policy:
--      (role() = 'authenticated' and (auth.uid() = (storage.foldername(name))[1]::uuid))
-- =========================================================================
